Check whether to skip lengthy check at init; show cmd

diff --git a/trccmd b/trccmd
--- a/trccmd
+++ b/trccmd
@@ -9,7 +9,7 @@
 # As an additional feature, the binary data file generated by trace-cmd(1),
 # can be imported into the Trace Compass GUI and better visualized.
 # Details here: using_tracecompass_gui_with_trccmd.txt
-# (online: https://github.com/kaiwan/L5_debug_trg/blob/master/kernel_debug/tracing/ftrace/using_tracecompass_gui_with_trccmd.txt)
+# (online: https://github.com/kaiwan/trccmd/blob/main/using_tracecompass_gui_with_trccmd.txt)
 #
 # (c) Kaiwan N Billimoria, kaiwanTECH
 # License: MIT
@@ -30,6 +30,7 @@ source ${CONFIG} || {
 (Please ensure you 'git clone' the full repo to get the config file as well!)"
  exit 1
 }
+echo "config: ${CONFIG}"
 
 usage()
 {
@@ -69,20 +70,31 @@ if [ $? -ne 0 ] ; then
 fi
 echo " [OK] (ftrace loc: ${TRCMNT})"
 
-echo -n "[+] Checking for trace-cmd with function_graph plugin support, pl wait ..."
-which trace-cmd >/dev/null 2>&1 || {
-  echo "${name}: trace-cmd not installed (or not in PATH)?"
-  exit 1
-}
 #-------------- test for the 'function_graph' plugin support
-mv trace.dat trace.dat.bkp 2>/dev/null
-sudo trace-cmd record -p function_graph -l kmem_cache_alloc -F true / >/dev/null 2>&1 || {
-  echo "${name}: trace-cmd didn't work with the function-graph plugin, aborting..."
-  exit 2
-}
-sudo rm -f trace.dat 2>/dev/null
-mv trace.dat.bkp trace.dat 2>/dev/null
-echo " [OK]"
+if [ ${SKIP_FTRACE_CHECK} -eq 0 ]; then
+ echo -n "[+] Checking for trace-cmd with function_graph plugin support, pl wait ..."
+ which trace-cmd >/dev/null 2>&1 || {
+   echo "${name}: trace-cmd not installed (or not in PATH)?"
+   exit 1
+ }
+
+ mv trace.dat trace.dat.bkp 2>/dev/null
+ TESTFUNC=__do_sys_getpid
+ if ! sudo grep -q -w ${TESTFUNC} ${TRCMNT}/available_filter_functions ; then
+   echo "${name}: test func ${TESTFUNC} not available, aborting test..."
+   exit 4
+ else
+  sudo trace-cmd record -p function_graph -l ${TESTFUNC} -F true >/dev/null 2>&1 || {
+    echo "${name}: trace-cmd didn't work with the function-graph plugin, aborting..."
+    exit 5
+  }
+ fi
+ sudo rm -f trace.dat 2>/dev/null
+ mv trace.dat.bkp trace.dat 2>/dev/null
+ echo " [OK]"
+else
+ echo "[.] config: skip lengthy ftrace function_graph check"
+fi
 
 #------------------ RECORD
 TRC_FILE_BINARY=trc_all.dat
@@ -108,23 +120,27 @@ echo "[+] Recording now ...(binary ftrace file is ${TRC_FILE_BINARY}
 [rec options: \"${OPTS_RECORD}\"]
 
 << This can take a while, be patient ...
-Also, if you must, hit Ctrl^C just once to abort recording >>
+ (Pl at least wait for a message onscreen before doing anything)
+Also, if you must abort, hit Ctrl^C just once >>
 "
 if [ $# -ge 1 ] ; then
-  sudo trace-cmd record ${OPTS_RECORD} -c -F "$@"
+  cmd="sudo trace-cmd record ${OPTS_RECORD} -c -F "$@""
    # -F: trace only this executable
    # -c: ...along with it's children, if any
 else
-  sudo trace-cmd record ${OPTS_RECORD}
+  cmd="sudo trace-cmd record ${OPTS_RECORD}"
 fi
 
+echo "> ${cmd}"
+eval ${cmd}
 [ $? -ne 0 ] && {
   echo "${name}: 'trace-cmd record' failed, aborting ..."
-  exit 4
+  exit 6
 }
+
 ls "${TRC_FILE_BINARY}" >/dev/null || {
   echo "${name}: 'trace-cmd record' failed, no binary trace file, aborting ..."
-  exit 5
+  exit 7
 }
 sudo chown ${USER}:${USER} ${TRC_FILE_BINARY}
 
@@ -135,12 +151,15 @@ OPTS_REPORT="-l -i ${TRC_FILE_BINARY}"
  # -l : adds a "latency output" format
  # -i : input file spec
 [ ${QUIET_MODE} -eq 1 ] && OPTS_REPORT="${OPTS_REPORT} -q"
-[ ${DONT_REPORT_IRQCTX} -eq 1 ] && {
+[ ${REPORT_IRQCTX} -eq 0 ] && {
   echo ", *leaving out* interrupt contexts"
   OPTS_REPORT="${OPTS_REPORT} -I -S"
 }
 
-trace-cmd report ${OPTS_REPORT} > "${TRC_FILE}"
+cmd="trace-cmd report ${OPTS_REPORT} > "${TRC_FILE}""
+echo "
+> ${cmd}"
+eval ${cmd}
 [ $? -ne 0 ] && {
     echo "${name}: 'trace-cmd report' failed, aborting ..."
     exit 6
